name: diabetes_tracker
description: "A Flutter application to track diabetes metrics and calculate insulin dosages."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.6


flutter:
  uses-material-design: true
